### PR TITLE
Add severity to all rules

### PR DESCRIPTION
**Pull request by rw-access**

### CODE REVIEW

**Review by jkamdjou — COMMENTED** [review]
Many of these rules already have a `severity` field, so there's 2 now :/

**Comment by jkamdjou** [comment]
> Many of these rules already have a `severity` field, so there's 2 now :/

i can make the updates in like 30 minutes

**Comment by jkamdjou** [comment]
> Many of these rules already have a `severity` field, so there's 2 now :/

i can make the updates in like 45 minutes

**Review by jkamdjou — APPROVED** [review]

**Review by ianthiel — APPROVED** [review]
🔥

**Pull request merged**
