### PR TITLE
Updating Rule: updating regex to avoid FPs

### PR DESCRIPTION
**Pull request by aidenmitchell**

### CODE REVIEW

**Review by jkamdjou — COMMENTED** [review]
lgtm, does it pass regression tests? i can't tell on mobile

**Comment by aidenmitchell** [comment]
Not sure, regression testing does not work on forks yet... we'll do some Shared Samples hunts to be safe.

**Comment by aidenmitchell** [comment]
14 day hunt in Shared Samples shows no regression, only email dropped is the FP.

**Review by morriscode — APPROVED** [review]
➕

**Pull request merged**
