### PR TITLE
New Rule: Fake DocuSign HTML table not linking to DocuSign domains

### PR DESCRIPTION
**Pull request by morriscode**
Alternative name: Brand Impersonation: DocuSign HTML Table Forgery

Open to suggestions.

### CODE REVIEW

**Comment by morriscode** [comment]
Not seeing this in the test-rules table.....

**Comment by morriscode** [comment]
Test rules are running, but I don't think this should be a blocker. This is pretty tightly scoped and has performed well in hunts already. FN coverage is solid.

**Comment by morriscode** [comment]
Testing looks solid, also matching user reports.

**Comment by morriscode** [comment]
Every test rule match has an AS of malicious, couldn't ask for better!

**Review by aidenmitchell — APPROVED** [review]

**Pull request merged**
