### PR TITLE
New Rule: HTML smuggling with Javascript hex array encoding

### PR DESCRIPTION
**Pull request by aidenmitchell**
FP test will be needed.

### CODE REVIEW

**Comment by aidenmitchell** [comment]
This rule is similar to https://github.com/sublime-security/sublime-rules/blob/main/detection-rules/attachment_html_smuggling_raw_buffer.yml

we might want to combine them?

**Comment by jkamdjou** [comment]
> This rule is similar to https://github.com/sublime-security/sublime-rules/blob/main/detection-rules/attachment_html_smuggling_raw_buffer.yml
> 
> we might want to combine them?

yeah that might be the way to go, can you tell why the other one didn't flag this attack?

**Comment by aidenmitchell** [comment]
The existing rule contains:
```
and any(.scan.strings.strings,
                    strings.contains(., ".map")
                )
```

which some payloads _don't_ contain. The rest of the rule works though.

**Comment by morriscode** [comment]
@jkamdjou  @aidenmitchell's version is firing on the html reported by MH yesterday. Rather then merge two, I think we can cut 'map' without an increase in FP's. Cutting map and including Aidens string as an OR matches both samples. 

`type.inbound and
  any(attachments,
        (
            .file_extension in~ ("html", "htm") or
            .file_extension in~ $file_extensions_common_archives or
            .file_type == "html"
        )
        and any(beta.binexplode(.),
                any(.scan.strings.strings,
                    // arrayBuffer, eg repetition:
                    // [0xa0,0x8e,0xd0,0x60,...]
                    regex.icontains(., '(\W?0x[a-zA-Z0-9]{2}\W?,\s*){100}')
                )
        or any(.scan.strings.strings,
                    regex.contains(., "(?:(?:0x).*?){30,}")
                )
        )
  )
  `
If you all are cool with it I'll update the other signature and we can kill this PRl

**Comment by morriscode** [comment]
Testing the hybrid rule bumped aidens repeat block to a min of 100 seems to work fine.

**Comment by morriscode** [comment]
Further testing indicates this looks distinct enough to stand on its own. thanks @aidenmitchell

**Review by morriscode — APPROVED** [review]
testing finalized, rule seems to hold true, while matching previously missed messages! approving

**Pull request merged**
