### PR TITLE
Update qr_code_suspicious_indicators.yml

### PR DESCRIPTION
**Pull request by aidenmitchell**
# Description

Negating contact cards in QR codes.

# Associated samples

- https://platform.sublime.security/messages/05bbb9e8309322d2fe1051ff3a9ef2fb13917dd8ac816017ba80f5f95ee2a7c0

### CODE REVIEW

**Comment by aidenmitchell** [comment]
/mql-mimic-exempt 111578,111602,112340,113081,114015,114016,114206,140048,143516,167058,173590,183062,188275,188917,215368,251033,268403,268404,268405,268407,268408,268409,268410,268412,268413,268414,268415,268416,268417,280268,282175,294686,294781,297476,297477,297478,297479,304666,326499,352269,352307,352789,352812,352816,352817,438966

**Comment by aidenmitchell** [comment]
/mql-mimic-exempt 110367,110786,112301,113550,115144,116335,129455,136611,136614,136615,136750,136751,136752,139681,140517,140518,143892,159340,159341,159342,178582,178583,178585,178586,178587,178588,178589,178590,178591,178592,178593,178594,178595,178596,178597,178598,178599,184836,184837,184840,187510,187511,187512,187513,187514,187515,187516,187517,187518,187519,187520,187521,187522,187523,187524,187525,187526,194812,221128,233791,234439,234440,234441,245973,245996,246003,246012,246238,268340,268343,268346,268349,268350,268355,268358,268363,268364,268366,268367,268373,268375,268379,268380,268384,268386,268388,268390,268391,268393,268394,268395,268396,268397,268398,268400,272602,272603,272604,272605

**Review by morriscode — APPROVED** [review]
Nice

**Pull request merged**
