### PR TITLE
Updating recipient.to checks to ensure domain is valid

### PR DESCRIPTION
**Pull request by aidenmitchell**

### CODE REVIEW

**Review by bfilar — APPROVED** [review]
Nice work!

**Review by morriscode — APPROVED** [review]

**Comment by morriscode** [comment]
Couple mimic failures after the last push. If you review those i think this is gtg. 
@aidenmitchell

**Comment by morriscode** [comment]
cc @aidenmitchell  looks like we got some conflicts now :/

**Pull request merged**
