### PR TITLE
Create attachment_html_javascript_HTTP.yml

### PR DESCRIPTION
**Pull request by zoomequipd**
# Description
Rule is designed to alert on HTML attachments which contain JavaScript function/keywords that support remote HTTP requests.

# Associated samples

- [Sample 1](https://platform.sublimesecurity.com/messages/46a8d662dd35be250a9642b807963c44fa4d7bb592186d02a396fd2e6d321144)
- [Sample 2](https://platform.sublimesecurity.com/messages/0304a14ffdc30fd04d4b31a827127aa56e5a10e96b8585ad0266aea218f2ac0c)
- [Sample 3](https://platform.sublimesecurity.com/messages/bbfdc9e7f5923670d5dd2627642c4f1aeb07ae55ce881f078d2b873c12aff50b)

## Associated hunts

- [Hunt 1](https://platform.sublimesecurity.com/hunts/8f376240-2c48-4506-87ad-3744156a8030)

### CODE REVIEW

**Comment by zoomequipd** [comment]
looks good pending https://github.com/sublime-security/static-files/pull/204

**Comment by zoomequipd** [comment]
https://github.com/sublime-security/static-files/pull/204 - merged, will give another couple days to let that change go through.

**Comment by zoomequipd** [comment]
looks good, requested review

**Review by morriscode — APPROVED** [review]

**Pull request merged**
