### PR TITLE
New Rule: VIP Impersonation via Google Group relay

### PR DESCRIPTION
**Pull request by morriscode**

### CODE REVIEW

**Comment by morriscode** [comment]
No hits on the new variation overnight. This is much tighter scoped by using org_vips!

**Comment by morriscode** [comment]
No hits on the new variation overnight. This is much tighter scoped by using org_vips!

**Comment by morriscode** [comment]
This is GTG

**Review by aidenmitchell — APPROVED** [review]

**Review by jkamdjou — APPROVED** [review]
🔥

**Pull request merged**
