### PR TITLE
Create impersonation_stripe.yml

### PR DESCRIPTION
**Pull request by zoomequipd**
# Description

Match on the display name of Stripe for impersonations

# Associated samples

- [Sample 1](https://platform.sublimesecurity.com/messages/efe0061f0fa1ae7bf6e7db7e3b1919d5b72a7fc9f82d8c068923763f53dec77c)

## Associated hunts

- [Hunt 1](https://platform.sublimesecurity.com/hunts/4e145262-8f34-46fe-a97f-3326e279a216)

### CODE REVIEW

**Comment by zoomequipd** [comment]
looks pretty low volume.  nothing in shared EMLs since deployed.  Will monitor for another week and then push if no negative feedback.

**Comment by zoomequipd** [comment]
no additional hits.

**Comment by zoomequipd** [comment]
looking good ready for review

**Review by morriscode — APPROVED** [review]

**Pull request merged**
