### PR TITLE
Create impersonation_mailgun.yml

### PR DESCRIPTION
**Pull request by zoomequipd**
# Description

rework of #1670  @peterdj45  please let me know what you think. 

# Associated samples

Only in body
- [Sample 1](https://platform.sublime.security/messages/3bfec629e6fbfd2324e29da97dd39efd1634980e22b164e05c308a7fecb593c1)
- [Sample 2](https://platform.sublime.security/messages/f50c4c20da191206ff8688650c8c75a479e31067472e21457d3a326e6a44ec72)

In Subject
- [Sample 1](https://platform.sublime.security/messages/3cb0aef3c75ebccca4bd14e09ef46c19f73a0771912d4b143d790583934bb649)

In Sender
- [Sample 1](https://platform.sublime.security/messages/afabc5adcdd1b6bd4d02d788dd33c5e9097469f0fb412522707f0bdd30b08e87)

## Associated hunts

- [Hunt 1](https://platform.sublime.security/hunts/4b4114f3-fe36-4493-990f-5f5c1f7659b8)

### CODE REVIEW

**Comment by peterdj45** [comment]
Looks good to me! Thank you for your help rewriting this.

**Comment by zoomequipd** [comment]
Updated hunt:
[Messages that will no longer match](https://platform.sublime.security/hunts/3b051b86-207a-456c-bfce-c01e5346c3fd)

**Comment by zoomequipd** [comment]
Test rules data is a bit inconclusive, but every commit has gotten better.  pretty low volume at this point.  L14 in Shared EMLs looks good.

**Review by morriscode — APPROVED** [review]

**Comment by morriscode** [comment]
Let's ship it if the volume looks low, we can continue to tweak as needed.

**Pull request merged**
