### PR TITLE
New rule - URI protocol handler: search-ms

### PR DESCRIPTION
**Pull request by jkamdjou**

### CODE REVIEW

**Comment by morriscode** [comment]
The last few test rule invocations you did errored out. Going to try once more

**Comment by morriscode** [comment]
This seems so specific, I have no issue approving just to get coverage out.

**Review by morriscode — APPROVED** [review]
👍

**Comment by jkamdjou** [comment]
> This seems so specific, I have no issue approving just to get coverage out.

@morriscode thank you! weird, i never got a notification for any of your replies. maybe cuz it was a comment and not a review comment? idk

**Pull request merged**
