### PR TITLE
New Rule: Executable embedded as an OLE object

### PR DESCRIPTION
**Pull request by aidenmitchell**
Detects executable files hidden inside Office documents.

### CODE REVIEW

**Comment by aidenmitchell** [comment]
Do we want to broaden this rule to include more file extensions, such as .pdf?

**Comment by aidenmitchell** [comment]
also worth noting, the `application/x-dbt` detection _should_ cover older Word documents with embedded batch files, but that data is based on a quick test I did, so it might be FP prone. If necessary, we can remove that MIME type, and do some more investigation.

**Comment by jkamdjou** [comment]
> also worth noting, the `application/x-dbt` detection _should_ cover older Word documents with embedded batch files, but that data is based on a quick test I did, so it might be FP prone. If necessary, we can remove that MIME type, and do some more investigation.

yeah looks like you were right, we're seeing a bunch of FPs on that

image

**Comment by jkamdjou** [comment]
looks like we get some FPs with `application/x-dosexec` :/

image

**Comment by aidenmitchell** [comment]
I'll do some investigating into that, I'm not too sure why a document would flag that type without containing an executable. Will update soon.

**Comment by aidenmitchell** [comment]
Any FPs on the `any(.scan.strings.strings, strings.ilike(., "*OLE Package*"))` part?

I did some more testing, the `text/x-msdos-batch` and `"OLE Package"` detections seem to be doing all of the heavy lifting anyway.

**Comment by morriscode** [comment]
Rule was updated to use new $file_extensions_executables list, but I think that's a 1x daily deployment. Will revisit tomorrow for backtesting.

**Comment by morriscode** [comment]
This fired 512 times in a hunt, all look to be benign messages.

**Comment by jkamdjou** [comment]
should we close this?

**Pull request closed without merging**
