### PR TITLE
New rule - Attachment: Embedded Javascript in SVG file (unsolicited)

### PR DESCRIPTION
**Pull request by jkamdjou**
Not sure how common this is in legit email, will def want to test.

Unsolicited should hopefully mitigate some. If we do see FPs, it'll prob be from unsolicited marketing emails pitching some service

### CODE REVIEW

**Comment by jkamdjou** [comment]
image

weird. will try again

**Comment by morriscode** [comment]
After reviewing test-rule results these look safe to ship!

**Pull request merged**
