### PR TITLE
New Rule: Fake Storage Alert

### PR DESCRIPTION
**Pull request by morriscode**

### CODE REVIEW

**Comment by morriscode** [comment]
Testing looks good here!

**Review by aidenmitchell — CHANGES_REQUESTED** [review]
Are we going to account for legit "Approaching SharePoint Site Storage Limit" emails? I see those surfacing in some envs.

**Comment by morriscode** [comment]
> Are we going to account for legit "Approaching SharePoint Site Storage Limit" emails? I see those surfacing in some envs.

Yeah I should probably do that. I saw a couple in but couldn't tell if they were legit or not

**Review by aidenmitchell — APPROVED** [review]

**Comment by morriscode** [comment]
Testing looks good, distribution is pretty even, some overlap with brand impersonation rules, this is net new coverage primarily.

**Pull request merged**
