### PR TITLE
Updating MS impersonation rule to include password expiry emails

### PR DESCRIPTION
**Pull request by aidenmitchell**
An example:
Screenshot 2022-07-06 at 3 39 24 PM

### CODE REVIEW

**Comment by aidenmitchell** [comment]
The new iteration is being weird for detection, so I'm working on that.
See https://sublimecommunity.slack.com/archives/C02N1F7FP7C/p1657161669007889 for more info.

**Comment by aidenmitchell** [comment]
This rule doesn't work on weird obfuscations of words, as we've discussed in the Slack community, but the rule still works. I'm good to push this iteration, and open a new PR once we have a solid idea on how to catch obfuscations easily.

cc @rw-access for this discovery in Slack

**Comment by jkamdjou** [comment]
thanks for this @aidenmitchell!

we're doing some testing on our side and will share results soon!

**Comment by aidenmitchell** [comment]
> This rule doesn't work on weird obfuscations of words, as we've discussed in the Slack community, but the rule still works. I'm good to push this iteration, and open a new PR once we have a solid idea on how to catch obfuscations easily.
> 
> cc @rw-access for this discovery in Slack

That's been added in 0.31.2, with this PR open, I added it here instead of a new one :)

**Comment by jkamdjou** [comment]
just wanted to give a quick update on this. we've been doing some testing in larger environments and are detecting quite a few net-new attacks that weren't previously detected by this rule, which is awesome 🔥. we're also seeing some FPs, so we're working on tuning some of the logic to get a bit higher efficacy. hope to have another update to share soon!

thanks for your patience, @aidenmitchell !

**Comment by jkamdjou** [comment]
hey @aidenmitchell . does this version of the rule still flag your attack?

```
type.inbound
and (
  (
    ilike(subject.subject, '*Microsoft 365*') 
    and ilike(subject.subject, '*is expired*')
  )
or
  (
    // should catch any instance of the word "expired"
    ilike(body.html.display_text, "*expir*")
    and ilike(body.html.display_text, "*password*")
    and ilike(body.html.display_text, "*microsoft*")
  )
  or iregex_search(body.html.display_text, ".*reach you.*microsoft teams")
  or ilike(sender.display_name, '*new activity in Teams*')
  or subject.subject =~ 'Offline Message in Teams'
  or ilike(subject.subject, '*Teams Sent A Message')
  or sender.display_name in~ ('Microsoft Partner Network','Microsoft',
                             'Microsoft Feedback', 'Microsoft account team',
                             'Microsoft Support', 'Microsoft 365 Message center', 
                             'Microsoft Azure')
)                                                                                                                         
and sender.email.domain.root_domain not in~ ('microsoft.com', 'microsoftsupport.com', 'office.com')

and (
    (
        sender.email.domain.root_domain in $free_email_providers
        and sender.email.email not in $sender_emails
    )
    or (
        sender.email.domain.root_domain not in $free_email_providers
        and sender.email.domain.domain not in $sender_domains
    )
)
```

**Comment by aidenmitchell** [comment]
It looks right to me, unfortunately the original .eml I used to build this rule has been erased from our system.
I'm good to push this :)

**Comment by jkamdjou** [comment]
> It looks right to me, unfortunately the original .eml I used to build this rule has been erased from our system. I'm good to push this :)

awesome. made that update, and also added you as an author on the rule 😄

**Review by jkamdjou — APPROVED** [review]
thank you @aidenmitchell! 🎉

**Pull request merged**
