### PR TITLE
New Rule: Detect PDF attachments with links created with Python 

### PR DESCRIPTION
**Pull request by padey**
The goal of this detection rule is to ensure that PDF files generated with a Python and with one or more links in the PDF are detected. These techniques were used by PikaBot (they used ReportLab), among others.

### CODE REVIEW

**Comment by morriscode** [comment]
thanks @padey. Will initiate some testing on this right now

**Comment by padey** [comment]
@morriscode thanks! My testpool is pretty limited / small. I'm excited what you think!

**Comment by morriscode** [comment]
Testing looks great here, I don't see any FP's. Going to approve

**Pull request merged**
