### PR TITLE
New rule - Spam: URL shortener with short body content and emojis

### PR DESCRIPTION
**Pull request by jkamdjou**

### CODE REVIEW

**Comment by morriscode** [comment]
Test rules still isn't consuming rules, this one included. 
I ran the rule in multiple environments and had no FP's or TP's. 
Consider this approved, but wanted to leave open incase we need a rule to test why test-rules is not consuming.

**Comment by jkamdjou** [comment]
> Test rules still isn't consuming rules, this one included. I ran the rule in multiple environments and had no FP's or TP's. Consider this approved, but wanted to leave open incase we need a rule to test why test-rules is not consuming.

@morriscode can i get that sweet ✅

**Review by morriscode — APPROVED** [review]

**Pull request merged**
