### PR TITLE
Multiple Open Redirects

### PR DESCRIPTION
**Pull request by zoomequipd**
# Description

Multiple open redirects observed ITW with malicious use

# Associated samples
- [Acoustic](https://platform.sublimesecurity.com/messages/25c2a4ca02475adbf540cad0df8edf9ae96b26bb1f74deadb85059086d28cee2)
- [bestdeals.today](https://platform.sublimesecurity.com/messages/81657660621d96145be397db8f2eb8ed0addb6b18f235bf5872f3bc640cf5c6e) - Second in an open redirect chain
- [Club-OS](https://platform.sublimesecurity.com/messages/e0aa56b7d332c3ca5433e89b04b6dc8004d0b527532288191ce9f5073c5b4ba8) - second in an open redirect chain
 - [documentmailbox](https://platform.sublimesecurity.com/messages/cd06420c1c37aa03b2704930fece9a13ec9055d6d89119c723ec6d9c57ab7efc)
 - [g7.fr](https://platform.sublimesecurity.com/messages/41e2cfd84968e4b1eaea4a3a928151e3d7be75dd7e27231a750a79c76e9bc66e)
 - [IndiaTimes](https://platform.sublimesecurity.com/messages/b7fcd2a6efd0555a8cc68e58f11e85b61b79ef7a9b631027c8e2700ce1a7429d)
 - [isadatalabs](https://platform.sublimesecurity.com/messages/81657660621d96145be397db8f2eb8ed0addb6b18f235bf5872f3bc640cf5c6e)
 - [ExacTag](https://platform.sublimesecurity.com/messages/70a6c88c4de454f12c132f0cf304bf07f1df4dd50c9ffff4293794bcb457d441)
 - [PremierBet](https://platform.sublimesecurity.com/messages/507fb200a36fd48484565d523602b23ad3f74c47147e39c09bc7f2d5d6432e47)
 - [ust.hk](https://platform.sublimesecurity.com/messages/30667d298b0fd148611b9f05c03c26d7a2b0dc804b790f3559b4752dae97ee7f)
 - [LeariningApps](https://platform.sublimesecurity.com/messages/c8c44f997ca1bee907406076e8d0cf5d06f7d323044b24d08d02702e4605fa23)
 - [Medium](https://platform.sublimesecurity.com/messages/6d1514bc2b3a4e18e6010de7ee73abe28025fe58e24e20c059457cb465fabff5)
 - [chkc](https://platform.sublimesecurity.com/messages/495254e4c0a05aeab53e4e6a57762c6549f5ffcddd0b3ae353c58f774bdceb56)

### CODE REVIEW

**Comment by zoomequipd** [comment]
Edited description of the Acoustic rule to make it more clear it's an ASR rule. 
All other rules look good in test rules / shared samples or have no hits in the last 7 days.

**Comment by zoomequipd** [comment]
Acoustic rule has FPs, was an ASR rule, but opted to just delete it so I can get the rest of these pushed.  Acoustic might be better as a url decoder

**Review by aidenmitchell — APPROVED** [review]

**Pull request merged**
