### PR TITLE
New Rule: Fake shipping notification with suspicious language

### PR DESCRIPTION
**Pull request by aidenmitchell**

### CODE REVIEW

**Comment by jkamdjou** [comment]
> [June 5, 2023 5:02 AM](https://www.notion.so/June-5-2023-5-02-AM-db4429d2e7d7498ca428979b0b00ee1f?pvs=8&n=github_linkback)

@morriscode @aidenmitchell this doesn't seem to be flagging the samples

**Comment by morriscode** [comment]
@jkamdjou this is firing the sample you linked now, we (@aidenmitchell) suspect this is due to NLU regression that has been remediated.

**Review by morriscode — APPROVED** [review]
No FP's in testing over the last 3 weeks.

**Comment by morriscode** [comment]
No hits in testing over the last 3 weeks. Should be safe to deploy.

**Pull request merged**
