### PR TITLE
Update attachment_office_remote_doc_template.yml

### PR DESCRIPTION
**Pull request by morriscode**
Tightening regex scope

### CODE REVIEW

**Comment by jkamdjou** [comment]
@morriscode i don't see any files changed here

**Comment by morriscode** [comment]
Helps to commit

**Comment by morriscode** [comment]
mimic failure is on a phishing test, investigating now to make sure i didn't tighten it too hard

**Comment by morriscode** [comment]
gtg here

**Review by aidenmitchell — APPROVED** [review]

**Pull request merged**
