### PR TITLE
Add logo detection, remove FTS

### PR DESCRIPTION
**Pull request by jkamdjou**

### CODE REVIEW

**Comment by morriscode** [comment]
Did you want to include "*storage*" in the first strings set and "*exceeded*" in the second set. It doesn't match any in our repo but it does match on others I've seen. 

Sorry I'm on my phone or I'd suggest it.

**Comment by jkamdjou** [comment]
> Did you want to include "_storage_" in the first strings set and "_exceeded_" in the second set. It doesn't match any in our repo but it does match on others I've seen.
> 
> Sorry I'm on my phone or I'd suggest it.

@morriscode holy shit i didn't see your comment until just now but i literally just pushed that

**Review by morriscode — APPROVED** [review]
🔨 #nailedit

**Comment by jkamdjou** [comment]
> 🔨 #nailedit

image

**Pull request merged**
