### PR TITLE
Add .ppt to the file extension lists

### PR DESCRIPTION
**Pull request by aidenmitchell**
Adding .ppt to all of the VBA macro detections

### CODE REVIEW

**Comment by aidenmitchell** [comment]
Just saw #181... assuming .ppt is in the $file_extensions_macros list, this PR is redundant 😅

**Comment by jkamdjou** [comment]
nice! here's where the new list is pulling from: https://github.com/sublime-security/static-files/blob/master/file_extensions_macros.txt

do you by chance have a `.ppt` payload that runs macros on hand that we can test/verify with?

**Comment by jkamdjou** [comment]
> nice! here's where the new list is pulling from: https://github.com/sublime-security/static-files/blob/master/file_extensions_macros.txt
> 
> do you by chance have a `.ppt` payload that runs macros on hand that we can test/verify with?

or even just a reference link that .ppt files support macros would be great

**Comment by jkamdjou** [comment]
Just synced up with @ajpc500 to confirm the following are all missing: wbk, ppa, ppam, ppt

Let's get these added to the [source repo list](https://github.com/sublime-security/static-files), and then i think we can close this one out.

@aidenmitchell do you want to make the PR there? i'm also happy to!

**Comment by aidenmitchell** [comment]
@jkamdjou sounds good, I'll open that PR.

**Comment by aidenmitchell** [comment]
Closing in favor of https://github.com/sublime-security/sublime-rules/pull/183

**Pull request closed without merging**
