### PR TITLE
Create abuse_hellosign_sus_names.yml

### PR DESCRIPTION
**Pull request by zoomequipd**
# Description

add coverage for HelloSign Abuse

# Associated samples

- [Sample 1](https://platform.sublime.security/messages/f08b64ccf0615d716f70276d6dc41e2eb0a748837d16cda5afa2a139cd28cd1c)

## Associated hunts

- [Hunt 1](https://platform.sublime.security/hunts/5f46da74-501f-4681-a725-ccd61acdbaa8)

### CODE REVIEW

**Comment by zoomequipd** [comment]
looking good within shared samples and test rules

**Review by morriscode — APPROVED** [review]

**Pull request merged**
