### PR TITLE
Update body_advance_fee_new_sender.yml

### PR DESCRIPTION
**Pull request by morriscode**

### CODE REVIEW

**Comment by aidenmitchell** [comment]
@morriscode some Mimic failures here, should they be fixed?

**Comment by morriscode** [comment]
/mql-mimic-exempt: 34360, 34071, 34042, 34073, 33936, 33746, 33722, 33733, 33724, 33536


Checked several of these and they were QR codes or MS impersonation. The ones reporting 0 rules matching actually fire 3 rules

**Comment by morriscode** [comment]
/mql-mimic-exempt: 34360, 34071, 34042, 34073, 33936, 33746, 33722, 33733, 33724, 33536, 30310, 30374, 30357, 30372, 30387, 30519, 30520, 30829, 30866, 33531

**Review by aidenmitchell — APPROVED** [review]

**Pull request merged**
